config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'

  resources :accounts do
    resources :cards, only: [:index] do
      put :freeze
      put :unfreeze
    end

    resources :transactions, only: [:index, :show] do
      collection do
        get :map
        get :list        
      end
    end
  end

  resources :sessions, only: [:new] do
    collection do
      get :callback
    end
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController

  skip_before_action :ensure_account

  def index
    @accounts = mondo.accounts
    if @accounts.count == 1
      return redirect_to account_transactions_path(@accounts.first.id)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_filter :authenticate
  before_action :ensure_account

  helper_method :balance
  helper_method :account_id
  attr_accessor :account_id

  rescue_from 'Mondo::ApiError' do |exception|
    raise if Rails.env.development?

    logout!
    redirect_to new_session_path
  end

  def ensure_account
    @account_id = params[:account_id]
    redirect_to accounts_path unless @account_id
  end

  def balance
    @_balance ||= mondo.balance(account_id)
  end

  def logout!
    cookies.delete :mondo_token
  end

  def mondo
    MondoService.new(cookies.signed[:mondo_token], account_id)
  end

  def authenticate
    redirect_to new_session_path unless cookies.signed[:mondo_token]
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  def index
    @cards = mondo.cards(account_id: account_id)
  end

  def freeze
    @card = mondo.cards(account_id: account_id).select { |c| c.id == params[:card_id] }.first
    @card.freeze
    redirect_to :back
  end

  def unfreeze
    @card = mondo.cards(account_id: account_id).select { |c| c.id == params[:card_id] }.first
    @card.unfreeze
    redirect_to :back
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  skip_before_filter :authenticate, only: [:new, :callback]
  skip_before_action :ensure_account, only: [:new, :callback]

  def new
    if cookies.signed[:mondo_token]
      redirect_to accounts_path
    else
      redirect_to MondoService.authorize_url(redirect_uri: callback_sessions_url)
    end
  end

  def callback
    if params[:code]
      token = MondoService.token_from_code(params[:code], redirect_uri: callback_sessions_url)
      cookies.permanent.signed[:mondo_token] = {
       value: token,
       secure: false
      }
    end

    redirect_to accounts_path
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  def index
  end

  def list
    @transactions = mondo.transactions(expand: [:merchant], account_id: account_id, since: 7.days.ago.utc.strftime('%FT%TZ'))
    render 'list', layout: false
  end

  def show
    @transaction = mondo.transaction(params[:id])
  end

  def map
    @transactions = mondo
      .transactions(expand: [:merchant], account_id: account_id, since: 30.days.ago.utc.strftime('%FT%TZ'))
      .select { |t| t.merchant && !t.merchant.online?  }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def async_partial(url)
    content_tag :div, data: { 'async-partial': url } do
      tag :p, class: 'loader'
    end
  end

  def transaction_logo(transaction)
    transaction.merchant.try(:logo).presence || "http://placehold.it/60x60?text=#{transaction.merchant.try(:name)}"
  end

end

app/views/accounts/index.html.haml
.container
  %table.table
    %tr
      %th Account
      %th Balance

    - @accounts.each do |account|
      %tr
        %td= link_to account.description, account_transactions_path(account.id)
        %td= account.balance.balance.format

app/views/cards/index.html.haml
.container
  %table.table
    %tr
      %th Card
      %th Expires
      %th Status
      %th Action

    - @cards.each do |card|
      %tr
        %td= card.last_digits
        %td= card.expires
        %td= card.status.titleize
        %td
          - if card.active?
            = link_to 'Freeze', account_card_freeze_path(account_id, card.id), method: :put, class: 'btn btn-xs btn-danger'
          - else
            = link_to 'Unfreeze', account_card_unfreeze_path(account_id, card.id), method: :put, class: 'btn btn-xs btn-success'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Monzo
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %nav.navbar.navbar-default.navbar-fixed-top
      .container-fluid
        .navbar-header
          %button.navbar-toggle.collapsed{"aria-expanded" => "false", "data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.navbar-brand{:href => "#"} Monzo
        #bs-example-navbar-collapse-1.collapse.navbar-collapse
          %ul.nav.navbar-nav
            = active_link_to 'Accounts', accounts_path, wrap_tag: :li, active: :exclusive
            - if account_id
              = active_link_to 'Transactions', account_transactions_path(account_id), wrap_tag: :li, active: :exclusive
              = active_link_to 'Map', map_account_transactions_path(account_id), wrap_tag: :li
              = active_link_to 'Cards', account_cards_path(account_id), wrap_tag: :li
    = yield

app/views/transactions/_map_js.html.erb
<script>
$(document).ready(function() {
  var map = L.map('map', {
  })

  var bounds = new L.LatLngBounds([
    <% @transactions.each do |transaction| %>
      [<%= transaction.merchant.address.latitude %>, <%= transaction.merchant.address.longitude%>],
    <% end %>
  ]);

  map.fitBounds(bounds);

  L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png', {
      attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
  }).addTo(map);


  <% @transactions.each do |transaction| %>
    var icon = L.icon({
        iconUrl: '<%= transaction_logo(transaction) %>',
        iconRetinaUrl: '<%= transaction_logo(transaction) %>',
        iconSize: [38, 38],
        iconAnchor: [22, 70],
        popupAnchor: [-3, -76],
        shadowSize: [68, 95],
        shadowAnchor: [22, 94]
    });

    L.marker([<%= transaction.merchant.address.latitude %>, <%= transaction.merchant.address.longitude%>], { icon: icon }).addTo(map)
        .bindPopup("<%= transaction.merchant.name %>");
  <% end %>

});

</script>

app/views/transactions/index.html.haml
.container
  = async_partial list_account_transactions_path(account_id)

app/views/transactions/list.html.haml
.row
  .col-md-6
    %h1.lead Balance: #{balance.balance.format}
  .col-md-6
    %h1.lead{style: 'text-align: right'} Spent Today: #{balance.spent_today.format}

%table.table
  %tr
    %th Merchant
    %th Date
    %th Category
    %th Amount
    %th Balance
  - @transactions.each do |transaction|
    %tr
      %td
        = image_tag transaction_logo(transaction), width: 20
        = link_to (transaction.merchant.try(:name) || (transaction.is_load ? 'Topup' : 'Unknown')), account_transaction_path(account_id, transaction.id)
        - if transaction.declined?
          %span.text-danger= '(delined)'
      %td= transaction.created.to_s(:short)
      %td
        = transaction.category.titleize
        = transaction.merchant.try(:emoji)
      %td{class: transaction.amount.to_i > 0 ? 'alert-success' : 'alert-danger'}
        = transaction.amount.format
      %td= transaction.account_balance.format

app/views/transactions/map.html.haml
#map{style: 'width: 100%; height: 500px; margin-top: -20px; margin-bottom: 20px;'}
= render 'map_js'

app/views/transactions/show.html.haml
- unless @transaction.merchant.online
  #map{style: 'width: 100%; height: 250px; margin-top: -20px; margin-bottom: 20px;'}
  :javascript
    $(document).ready(function() {
      var map = L.map('map', {
        scrollWheelZoom: false,
        touchZoom: false,
        dragging: false
      }).setView([#{@transaction.merchant.address.latitude}, #{@transaction.merchant.address.longitude}], 13);

      L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png', {
          attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
      }).addTo(map);

      var icon = L.icon({
          iconUrl: '#{transaction_logo(@transaction)}',
          iconRetinaUrl: '#{transaction_logo(@transaction)}',
          iconSize: [38, 38],
          iconAnchor: [22, 70],
          popupAnchor: [-3, -76],
          shadowSize: [68, 95],
          shadowAnchor: [22, 94]
      });

      L.marker([#{@transaction.merchant.address.latitude}, #{@transaction.merchant.address.longitude}], { icon: icon }).addTo(map)
          .bindPopup("#{@transaction.merchant.name}")
          .openPopup();
    })

.container

  - if @transaction.declined?
    %p.alert.alert-danger= "This transaction was declined. The reason given was: #{@transaction.decline_reason}"

  #h1.lead
    %img{src: transaction_logo(@transaction), style: 'width: 30px'}
    = "#{@transaction.amount.abs.format} at #{@transaction.merchant.name}"

  - if @transaction.notes.present?
    %p.well.well-sm= @transaction.notes

  %table.table
    %tr
      %th Date
      %td= @transaction.created.to_s(:short)
    %tr
      %th Description
      %td= @transaction.description
    %tr
      %th Amount
      %td= @transaction.amount.format
    %tr
      %th Category
      %td
        = @transaction.category.titleize
        = @transaction.merchant.try(:emoji)
    %tr
      %th Balance
      %td= @transaction.account_balance.format
    %tr
      %th Address
      %td= @transaction.merchant.address.short_formatted


  - if @transaction.attachments.any?
    %hr
    - @transaction.attachments.each do |attachment|
      .col-xs-6.col-md-3
        %a{href: attachment.url}
          .thumbnail
            %img{src: attachment.url, style: 'width: 250px'}